class Stack:
    def __init__(self):
        self.items = []
    def push(self, item):
        self.items.append(item)
    def pop(self):
        return self.items.pop(0)

stack = Stack()
stack.push("A")
stack.push("B")
stack.push("C")
stack.push("D")
stack.push("E")
stack.push("F")
print("Part 3.2.2: First  Stack is: ")
print("Stack: ", end="")
print(stack.items)
stack.pop()
print("FIFO: ", end="")
print(stack.items)
stack.pop()
print("FIFO: ", end="")
print(stack.items)
stack.pop()
print("FIFO: ", end="")
print(stack.items)
stack.pop()
print("FIFO: ", end="")
print(stack.items)
stack.pop()
print("FIFO: ", end="")
print(stack.items)
stack.pop()
print("FIFO: ", end="")
print(stack.items)
stack = Stack()
print("====================================")
print("Part 3.2.2: Stack reverse is:")
stack.push("F")
print("FIFO: ", end="")
print(stack.items)
stack.push("E")
print("FIFO: ", end="")
print(stack.items)
stack.push("D")
print("FIFO: ", end="")
print(stack.items)
stack.push("C")
print("FIFO: ", end="")
print(stack.items)
stack.push("B")
print("FIFO: ", end="")
print(stack.items)
stack.push("A")
print("Stack: ", end="")
print(stack.items)